import type { GameDefinition } from '@/engine/types';

export const patternTrailDefinition: GameDefinition = {
  slug: 'pattern-trail',
  title: 'Pattern Trail',
  description: 'Follow the glowing path through the woods',
  iconKey: 'target',
  category: 'pattern',
  worldSlug: 'forest-of-focus',
  sortOrderInWorld: 3,
  difficulty: ['easy', 'medium', 'hard'],
  timerMode: 'perRound',
  defaultDurationSec: 5,
  maxScore: 1000,
  supportsLives: true,
  maxLives: 3,
  supportsPause: true,
  difficultyConfig: {
    easy: { durationSec: 300, maxScore: 600, speed: 6, gridSize: 9, roundCount: 0, itemCount: 3 },
    medium: { durationSec: 300, maxScore: 800, speed: 5, gridSize: 9, roundCount: 0, itemCount: 4 },
    hard: { durationSec: 300, maxScore: 1000, speed: 4, gridSize: 16, roundCount: 0, itemCount: 4 },
  },
  primarySkill: 'patternRecognition',
  secondarySkills: ['memory', 'focus'],
  skillWeights: { patternRecognition: 0.5, memory: 0.35, focus: 0.15 },
  baseXp: 120,
  baseCoinReward: 30,
  diamondChance: 0.12,
  unlockLevel: 5,
  unlockWorldSlug: 'forest-of-focus',
  isOfflineCapable: true,
  isMultiplayerCapable: false,
  hasComboSystem: true,
  hasDifficultyRamp: true,
  accentColor: '#16A34A',
  instructions: [
    'Watch tiles light up in order',
    'Repeat the sequence exactly',
    'Each level adds more tiles',
    'Three mistakes ends the run',
  ],
};
