import type { GameDefinition } from '@/engine/types';

export const logicSprintDefinition: GameDefinition = {
  slug: 'logic-sprint',
  title: 'Logic Sprint',
  description: 'Solve equations on the forest trail',
  iconKey: 'lightning',
  category: 'math',
  worldSlug: 'forest-of-focus',
  sortOrderInWorld: 2,
  difficulty: ['easy', 'medium', 'hard'],
  timerMode: 'countdown',
  defaultDurationSec: 60,
  maxScore: 1000,
  supportsLives: true,
  maxLives: 3,
  supportsPause: true,
  difficultyConfig: {
    easy: { durationSec: 60, maxScore: 600, speed: 1, itemCount: 20 },
    medium: { durationSec: 60, maxScore: 800, speed: 1.3, itemCount: 50 },
    hard: { durationSec: 60, maxScore: 1000, speed: 1.6, itemCount: 100 },
  },
  primarySkill: 'logic',
  secondarySkills: ['reaction', 'focus'],
  skillWeights: { logic: 0.5, reaction: 0.3, focus: 0.2 },
  baseXp: 110,
  baseCoinReward: 28,
  diamondChance: 0.12,
  unlockLevel: 3,
  unlockWorldSlug: 'forest-of-focus',
  isOfflineCapable: true,
  isMultiplayerCapable: false,
  hasComboSystem: true,
  hasDifficultyRamp: true,
  accentColor: '#38BDF8',
  instructions: [
    'Solve each equation quickly',
    'Enter the answer and press Enter',
    'Wrong answers cost a life',
    'Speed boosts your score',
  ],
};
