import type { GameDefinition } from '@/engine/types';

export const memoryGroveDefinition: GameDefinition = {
  slug: 'memory-grove',
  title: 'Memory Grove',
  description: 'Match pairs among the forest symbols',
  iconKey: 'brain',
  category: 'memory',
  worldSlug: 'forest-of-focus',
  sortOrderInWorld: 1,
  difficulty: ['easy', 'medium', 'hard'],
  timerMode: 'countdown',
  defaultDurationSec: 60,
  maxScore: 1000,
  supportsLives: false,
  maxLives: 0,
  supportsPause: true,
  difficultyConfig: {
    easy: { durationSec: 60, maxScore: 600, gridSize: 12, itemCount: 6 },
    medium: { durationSec: 90, maxScore: 800, gridSize: 16, itemCount: 8 },
    hard: { durationSec: 120, maxScore: 1000, gridSize: 20, itemCount: 10 },
  },
  primarySkill: 'memory',
  secondarySkills: ['focus', 'patternRecognition'],
  skillWeights: { memory: 0.6, focus: 0.25, patternRecognition: 0.15 },
  baseXp: 110,
  baseCoinReward: 28,
  diamondChance: 0.12,
  unlockLevel: 5,
  unlockWorldSlug: 'forest-of-focus',
  isOfflineCapable: true,
  isMultiplayerCapable: false,
  hasComboSystem: true,
  hasDifficultyRamp: false,
  accentColor: '#22C55E',
  instructions: [
    'Flip cards to reveal forest symbols',
    'Find every matching pair',
    'Beat the clock on all three levels',
    'Build combos for bonus points',
  ],
};
